from myproject.wsgi import *
from home.models import *
from django.utils import timezone

def convert_vietnamese_accent_to_english(text):
    """
    Convert Vietnamese accents to English
    """
    text = text.lower()
    vietnamese_accents = {
        'à': 'a', 'á': 'a', 'ả': 'a', 'ã': 'a', 'ạ': 'a',
        'ă': 'a', 'ằ': 'a', 'ắ': 'a', 'ẳ': 'a', 'ẵ': 'a', 'ặ': 'a',
        'â': 'a', 'ầ': 'a', 'ấ': 'a', 'ẩ': 'a', 'ẫ': 'a', 'ậ': 'a',
        'đ': 'd',
        'è': 'e', 'é': 'e', 'ẻ': 'e', 'ẽ': 'e', 'ẹ': 'e',
        'ê': 'e', 'ề': 'e', 'ế': 'e', 'ể': 'e', 'ễ': 'e', 'ệ': 'e',
        'ì': 'i', 'í': 'i', 'ỉ': 'i', 'ĩ': 'i', 'ị': 'i',
        'ò': 'o', 'ó': 'o', 'ỏ': 'o', 'õ': 'o', 'ọ': 'o',
        'ô': 'o', 'ồ': 'o', 'ố': 'o', 'ổ': 'o', 'ỗ': 'o', 'ộ': 'o',
        'ơ': 'o', 'ờ': 'o', 'ớ': 'o', 'ở': 'o', 'ỡ': 'o', 'ợ': 'o',
        'ù': 'u', 'ú': 'u', 'ủ': 'u', 'ũ': 'u', 'ụ': 'u',
        'ư': 'u', 'ừ': 'u', 'ứ': 'u', 'ử': 'u', 'ữ': 'u', 'ự': 'u',
        'ỳ': 'y', 'ý': 'y', 'ỷ': 'y', 'ỹ': 'y', 'ỵ': 'y'
    }
    for k, v in vietnamese_accents.items():
        text = text.replace(k, v)
    text = text.title()
    return text


# import and create user
from django.contrib.auth.models import User
user = CustomUser.objects.create(
    email = 'minhlong2002@gmail.com',
    is_staff = True,
    is_active = True,
    is_superuser = True,
)

families = [{'id': 1,
  'family_name': 'Gia đình Lê Thế Bích',
  'origin': None,
  'family_history': None,
  'important_events': None,
  'family_tree_link': None},
 {'id': 2,
  'family_name': 'Gia đình Lê Minh Cầm',
  'origin': None,
  'family_history': None,
  'important_events': None,
  'family_tree_link': None}]

people = [{'id': 1,
  'full_name': 'Nguyễn Thị Thanh',
  'birth_date': '1953-12-10',
  'phone_number': '09774444879',
  'hobbies_interests': 'Nấu ăn',
  'occupation': None,
  'gender': False,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 2,
  'full_name': 'Lê Thế Bích',
  'birth_date': '1948-05-12',
  'phone_number': '0986006696',
  'hobbies_interests': 'Du lịch',
  'occupation': None,
  'gender': True,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 3,
  'full_name': 'Lê Nguyên Hoàng Sa',
  'birth_date': '1976-07-27',
  'phone_number': None,
  'hobbies_interests': 'Đọc sách',
  'occupation': 'Kinh Doanh Đồ Điện Tử',
  'gender': True,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 4,
  'full_name': 'Lê Nguyên Trường Sa',
  'birth_date': '1977-08-11',
  'phone_number': '0935123123',
  'hobbies_interests': 'Xã Hội',
  'occupation': 'Dược Sĩ',
  'gender': True,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 5,
  'full_name': 'Lê Nguyên Châu Sa',
  'birth_date': '1979-07-02',
  'phone_number': '0859299399',
  'hobbies_interests': 'Vô Vàn',
  'occupation': 'Vô Vàn',
  'gender': True,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 6,
  'full_name': 'Lê Nguyên Kim Sa',
  'birth_date': '1982-04-02',
  'phone_number': None,
  'hobbies_interests': 'Ngôn Ngữ',
  'occupation': 'Lập Trình Python',
  'gender': True,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 7,
  'full_name': 'Lê Nguyên Sa',
  'birth_date': '1984-02-04',
  'phone_number': '0974634567',
  'hobbies_interests': 'Đá Banh',
  'occupation': 'Kinh Doanh',
  'gender': True,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 8,
  'full_name': 'Lê Nguyên My Sa',
  'birth_date': '1990-10-12',
  'phone_number': None,
  'hobbies_interests': 'Kiếm Tiền',
  'occupation': 'Kinh Doanh Thời Trang',
  'gender': False,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1},
 {'id': 9,
  'full_name': 'Lê Thị Ngọc Cẩm',
  'birth_date': '1976-09-10',
  'phone_number': '0879232323',
  'hobbies_interests': 'Làm đẹp',
  'occupation': None,
  'gender': False,
  'contact_address': None,
  'nationality': None,
  'birth_place': None,
  'marital_status': None,
  'history': None,
  'achievement': None,
  'education_level': None,
  'health_status': None,
  'family_info': None,
  'profile_picture': None,
  'social_media_links': None,
  'family_id': 1}]

relationships = [{'id': 1,
  'person1_id': 2,
  'person2_id': 3,
  'relationship_type': "Ba",
  'start_date': None,
  'end_date': None,
  'type_id': 5},
 {'id': 2,
  'person1_id': 2,
  'person2_id': 4,
  'relationship_type': "Ba",
  'start_date': None,
  'end_date': None,
  'type_id': 5},
 {'id': 3,
  'person1_id': 2,
  'person2_id': 5,
  'relationship_type': "Ba",
  'start_date': None,
  'end_date': None,
  'type_id': 5},
 {'id': 4,
  'person1_id': 2,
  'person2_id': 7,
  'relationship_type': "Ba",
  'start_date': None,
  'end_date': None,
  'type_id': 5},
 {'id': 5,
  'person1_id': 2,
  'person2_id': 8,
  'relationship_type': "Ba",
  'start_date': None,
  'end_date': None,
  'type_id': 5},
 {'id': 1,
  'person1_id': 2,
  'person2_id': 1,
  'relationship_type': "Chồng",
  'start_date': None,
  'end_date': None,
  'type_id': 5},]

families_to_create = []
for family in families:
    families_to_create.append(Families(
        family_id=family['id'],
        family_name=family['family_name'],
        origin=family['origin'],
        family_history=family['family_history'],
        important_events=family['important_events'],
        family_tree_link=family['family_tree_link'],
    ))
Families.objects.bulk_create(families_to_create)

people_to_create = []
for person in people:
    birth_date = timezone.datetime.strptime(person['birth_date'], '%Y-%m-%d').date()
    people_to_create.append(People(
        people_id=person['id'],
        full_name_vn=person['full_name'],
        full_name=convert_vietnamese_accent_to_english(person['full_name']),
        birth_date=birth_date,
        phone_number=person['phone_number'],
        hobbies_interests=person['hobbies_interests'],
        occupation=person['occupation'],
        gender=person['gender'],
        contact_address=person['contact_address'],
        nationality=person['nationality'],
        birth_place=person['birth_place'],
        marital_status=person['marital_status'],
        history=person['history'],
        achievement=person['achievement'],
        education_level=person['education_level'],
        health_status=person['health_status'],
        family_info=person['family_info'],
        profile_picture=person['profile_picture'],
        social_media_links=person['social_media_links'],
    ))
People.objects.bulk_create(people_to_create)


for relationship in relationships:
    people = People.objects.get(people_id=relationship['person1_id']) #person1 là người đứng trước trong quan hệ person2
    people2 = People.objects.get(people_id=relationship['person2_id'])
    Relationships.objects.create(
        person1=people,
        person2=people2,
        relationship_type=relationship['relationship_type'],
    )

# birth_date = timezone.datetime.strptime('01-01-1922', '%d-%m-%Y').date()
# People.objects.create(
#     full_name_vn='Nguyễn Thị Dương',
#     full_name='Nguyen Thi Duong',
#     gender=False,
#     birth_date=birth_date,
# )
# birth_date = timezone.datetime.strptime('04-05-1919', '%d-%m-%Y').date()
# People.objects.create(
#     full_name_vn='Mạc Đinh Khang',
#     full_name='Mac Đinh Khang',
#     gender=True,
#     birth_date=birth_date, 
# )
# birth_date = timezone.datetime.strptime('10-10-1918', '%d-%m-%Y').date()

# People.objects.create(
#     full_name_vn='Lê Hùng Bá',
#     full_name='Le Hung Ba',
#     gender=True,
#     birth_date=birth_date, 
# )

# birth_date = timezone.datetime.strptime('10-10-1922', '%d-%m-%Y').date()
# People.objects.create(
#     full_name_vn='Nguyễn Thì Trường',
#     full_name='Nguyen Thi Truong',
#     gender=False,
#     birth_date=birth_date, 
# )

# birth_date = timezone.datetime.strptime('10-10-2002', '%d-%m-%Y').date()
# People.objects.create(
#     full_name_vn='Nguyễn Thị Hương',
#     full_name='Nguyen Thi Huong',
#     gender=False,
#     birth_date=birth_date,
# )

# birth_date = timezone.datetime.strptime('10-10-1978', '%d-%m-%Y').date()
# People.objects.create(
#     full_name_vn='Nguyễn Thị Thanh',
#     full_name='Nguyen Thi Thanh',
#     gender=False,
#     birth_date=birth_date,
# )