# Generated by Django 5.0.1 on 2024-02-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='leader',
        ),
        migrations.AddField(
            model_name='families',
            name='leader_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.people'),
        ),
    ]
