# Generated by Django 5.0.1 on 2024-02-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='families',
            name='family_img',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
