# Generated by Django 5.0.1 on 2024-01-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20240130_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Families',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=255)),
                ('origin', models.TextField()),
                ('family_history', models.TextField()),
                ('important_events', models.TextField()),
                ('family_tree_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_address', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=50)),
                ('history', models.TextField()),
                ('achievement', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('id_passport_number', models.CharField(max_length=50)),
                ('health_status', models.CharField(max_length=255)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('family_info', models.TextField()),
                ('profile_picture', models.TextField()),
                ('hobbies_interests', models.TextField()),
                ('social_media_links', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_person1', to='home.people')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_person2', to='home.people')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
