# Generated by Django 5.0.1 on 2024-01-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_families_people_relationships_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
