# Generated by Django 5.0.1 on 2024-01-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_people_birth_date_alter_people_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Families',
        ),
        migrations.RemoveField(
            model_name='people',
            name='id_passport_number',
        ),
        migrations.AlterField(
            model_name='people',
            name='achievement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='birth_place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='contact_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='education_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='family_info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='health_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='hobbies_interests',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='marital_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='profile_picture',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='social_media_links',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Relationships',
        ),
    ]
